import type { Team, Group, Match } from '@/types'

// ─── EQUIPOS ─────────────────────────────────────────────────────────────────
// CORRECCIÓN (auditoría 12 grupos): Eslovenia NO clasificó al Mundial 2026.
// El cuarto integrante real del Grupo K es Uzbekistán, confirmado contra
// 8 fuentes oficiales (FIFA.com, ESPN, CBS Sports, Sky Sports, Wikipedia, etc).

export const TEAMS: Team[] = [
  { flag:'🇲🇽', flagCode:'mx', name:'México',          slug:'mexico', coach:'Javier Aguirre',          group:'A', confederation:'CONCACAF',
    squad:[
      { number:1,  name:'Luis Malagón',        position:'GK',  club:'Club América' },
      { number:3,  name:'César Montes',         position:'DEF', club:'Lokomotiv' },
      { number:5,  name:'Johan Vásquez',        position:'DEF', club:'Genoa' },
      { number:4,  name:'Edson Álvarez',        position:'MID', club:'West Ham' },
      { number:24, name:'Luis Chávez',          position:'MID', club:'Dynamo Moscú' },
      { number:9,  name:'Santiago Giménez',     position:'FWD', club:'Feyenoord' },
      { number:10, name:'Alexis Vega',          position:'FWD', club:'Toluca' },
    ] },
  { flag:'🇿🇦', flagCode:'za', name:'Sudáfrica',       slug:'sudafrica', coach:'Hugo Broos',       group:'A', confederation:'CAF',
    squad:[
      { number:1,  name:'Ronwen Williams',      position:'GK',  club:'Mamelodi Sundowns' },
      { number:2,  name:'Khuliso Mudau',        position:'DEF', club:'Mamelodi Sundowns' },
      { number:3,  name:'Mothobi Mvala',        position:'DEF', club:'Mamelodi Sundowns' },
      { number:4,  name:'Teboho Mokoena',       position:'MID', club:'Mamelodi Sundowns' },
      { number:11, name:'Themba Zwane',         position:'MID', club:'Mamelodi Sundowns' },
      { number:10, name:'Percy Tau',            position:'FWD', club:'Al Ahly' },
      { number:9,  name:'Lyle Foster',          position:'FWD', club:'Burnley' },
    ] },
  { flag:'🇰🇷', flagCode:'kr', name:'Corea del Sur',   slug:'corea-del-sur', coach:'Hong Myung-bo',   group:'A', confederation:'AFC',
    squad:[
      { number:21, name:'Jo Hyeon-woo',         position:'GK',  club:'Ulsan HD' },
      { number:4,  name:'Kim Min-jae',          position:'DEF', club:'Bayern Múnich' },
      { number:22, name:'Seol Young-woo',       position:'DEF', club:'Red Star Belgrade' },
      { number:18, name:'Lee Kang-in',          position:'MID', club:'PSG' },
      { number:6,  name:'Hwang In-beom',        position:'MID', club:'Feyenoord' },
      { number:7,  name:'Son Heung-min',        position:'FWD', club:'Tottenham' },
      { number:11, name:'Hwang Hee-chan',       position:'FWD', club:'Wolverhampton' },
    ] },
  { flag:'🇨🇿', flagCode:'cz', name:'Rep. Checa',      slug:'rep-checa', coach:'Ivan Hasek',       group:'A', confederation:'UEFA',
    squad:[
      { number:1,  name:'Jindřich Staněk',      position:'GK',  club:'Slavia Praga' },
      { number:5,  name:'Vladimír Coufal',      position:'DEF', club:'West Ham' },
      { number:4,  name:'Ladislav Krejčí',      position:'DEF', club:'Girona' },
      { number:22, name:'Tomáš Souček',         position:'MID', club:'West Ham' },
      { number:7,  name:'Antonín Barák',        position:'MID', club:'Fiorentina' },
      { number:10, name:'Patrik Schick',        position:'FWD', club:'Bayer Leverkusen' },
      { number:9,  name:'Adam Hložek',          position:'FWD', club:'Hoffenheim' },
    ] },
  { flag:'🇨🇦', flagCode:'ca', name:'Canadá',          slug:'canada', coach:'Jesse Marsch',          group:'B', confederation:'CONCACAF',
    squad:[
      { number:16, name:'Maxime Crépeau',       position:'GK',  club:'Portland Timbers' },
      { number:19, name:'Alphonso Davies',      position:'DEF', club:'Bayern Múnich' },
      { number:2,  name:'Alistair Johnston',    position:'DEF', club:'Celtic' },
      { number:7,  name:'Stephen Eustáquio',    position:'MID', club:'Porto' },
      { number:8,  name:'Ismaël Koné',          position:'MID', club:'Marseille' },
      { number:10, name:'Jonathan David',       position:'FWD', club:'Lille' },
      { number:9,  name:'Cyle Larin',           position:'FWD', club:'Mallorca' },
    ] },
  { flag:'🇧🇦', flagCode:'ba', name:'Bosnia y Herz.',  slug:'bosnia', coach:'Sergej Barbarez',          group:'B', confederation:'UEFA',
    squad:[
      { number:1,  name:'Nikola Vasilj',        position:'GK',  club:'St. Pauli' },
      { number:3,  name:'Sead Kolašinac',       position:'DEF', club:'Atalanta' },
      { number:2,  name:'Amar Dedić',           position:'DEF', club:'Red Bull Salzburg' },
      { number:8,  name:'Benjamin Tahirović',   position:'MID', club:'Ajax' },
      { number:18, name:'Armin Gigović',        position:'MID', club:'Holstein Kiel' },
      { number:11, name:'Edin Džeko',           position:'FWD', club:'Fenerbahçe' },
      { number:10, name:'Ermedin Demirović',    position:'FWD', club:'Stuttgart' },
    ] },
  { flag:'🇨🇭', flagCode:'ch', name:'Suiza',           slug:'suiza', coach:'Murat Yakin',           group:'B', confederation:'UEFA',
    squad:[
      { number:21, name:'Gregor Kobel',         position:'GK',  club:'Borussia Dortmund' },
      { number:5,  name:'Manuel Akanji',        position:'DEF', club:'Manchester City' },
      { number:13, name:'Ricardo Rodríguez',    position:'DEF', club:'Betis' },
      { number:10, name:'Granit Xhaka',         position:'MID', club:'Bayer Leverkusen' },
      { number:8,  name:'Remo Freuler',         position:'MID', club:'Bologna' },
      { number:7,  name:'Breel Embolo',         position:'FWD', club:'Monaco' },
      { number:19, name:'Dan Ndoye',            position:'FWD', club:'Bologna' },
    ] },
  { flag:'🇶🇦', flagCode:'qa', name:'Qatar',           slug:'qatar', coach:'Marquez Lopez',           group:'B', confederation:'AFC',
    squad:[
      { number:22, name:'Meshaal Barsham',      position:'GK',  club:'Al-Sadd' },
      { number:3,  name:'Lucas Mendes',         position:'DEF', club:'Al-Wakrah' },
      { number:2,  name:'Pedro Miguel',         position:'DEF', club:'Al-Sadd' },
      { number:11, name:'Akram Afif',           position:'MID', club:'Al-Sadd' },
      { number:24, name:'Jassem Gaber',         position:'MID', club:'Al-Arabi' },
      { number:19, name:'Almoez Ali',           position:'FWD', club:'Al-Duhail' },
      { number:9,  name:'Yusuf Abdurisag',      position:'FWD', club:'Al-Sadd' },
    ] },
  { flag:'🇧🇷', flagCode:'br', name:'Brasil',          slug:'brasil',          group:'C', confederation:'CONMEBOL',
    worldCupBest:'Campeona del Mundo 1958, 1962, 1970, 1994 y 2002 · Récord absoluto de 5 títulos',
    coach:'Dorival Júnior',
    squad:[
      { number:1,  name:'Alisson Becker',      position:'GK',  club:'Liverpool' },
      { number:12, name:'Ederson',              position:'GK',  club:'Manchester City' },
      { number:23, name:'Bento',                position:'GK',  club:'Al-Qadsiah' },
      { number:2,  name:'Danilo',               position:'DEF', club:'Juventus' },
      { number:3,  name:'Marquinhos',           position:'DEF', club:'PSG' },
      { number:4,  name:'Gabriel Magalhães',    position:'DEF', club:'Arsenal' },
      { number:6,  name:'Alex Sandro',          position:'DEF', club:'Juventus' },
      { number:14, name:'Éder Militão',         position:'DEF', club:'Real Madrid' },
      { number:13, name:'Guilherme Arana',      position:'DEF', club:'Atlético Mineiro' },
      { number:22, name:'Vanderson',            position:'DEF', club:'AS Monaco' },
      { number:16, name:'Renan Lodi',           position:'DEF', club:'Flamengo' },
      { number:24, name:'Yan Couto',            position:'DEF', club:'Bournemouth' },
      { number:5,  name:'Casemiro',             position:'MID', club:'Manchester United' },
      { number:8,  name:'Bruno Guimarães',      position:'MID', club:'Newcastle' },
      { number:15, name:'João Gomes',           position:'MID', club:'Wolverhampton' },
      { number:7,  name:'Lucas Paquetá',        position:'MID', club:'West Ham' },
      { number:17, name:'Gerson',               position:'MID', club:'Flamengo' },
      { number:18, name:'Andreas Pereira',      position:'MID', club:'Fulham' },
      { number:25, name:'Douglas Luiz',         position:'MID', club:'Juventus' },
      { number:9,  name:'Richarlison',          position:'FWD', club:'Tottenham' },
      { number:10, name:'Rodrygo',              position:'FWD', club:'Real Madrid' },
      { number:11, name:'Raphinha',             position:'FWD', club:'Barcelona' },
      { number:20, name:'Endrick',              position:'FWD', club:'Real Madrid' },
      { number:21, name:'Gabriel Martinelli',   position:'FWD', club:'Arsenal' },
      { number:19, name:'Savinho',              position:'FWD', club:'Manchester City' },
      { number:26, name:'Luiz Henrique',        position:'FWD', club:'Botafogo' },
    ] },
  { flag:'🇲🇦', flagCode:'ma', name:'Marruecos',       slug:'marruecos', coach:'Walid Regragui',       group:'C', confederation:'CAF',
    squad:[
      { number:1,  name:'Yassine Bounou',       position:'GK',  club:'Al-Hilal' },
      { number:2,  name:'Achraf Hakimi',        position:'DEF', club:'PSG' },
      { number:5,  name:'Nayef Aguerd',         position:'DEF', club:'Real Sociedad' },
      { number:4,  name:'Sofyan Amrabat',       position:'MID', club:'Fenerbahçe' },
      { number:8,  name:'Azzedine Ounahi',      position:'MID', club:'Panathinaikos' },
      { number:10, name:'Brahim Díaz',          position:'FWD', club:'Real Madrid' },
      { number:19, name:'Youssef En-Nesyri',    position:'FWD', club:'Fenerbahçe' },
    ] },
  { flag:'🇭🇹', flagCode:'ht', name:'Haití',           slug:'haiti', coach:'Marc Collat',           group:'C', confederation:'CONCACAF',
    squad:[
      { number:1,  name:'Johny Placide',        position:'GK',  club:'Bastia' },
      { number:2,  name:'Carlens Arcus',        position:'DEF', club:'Angers' },
      { number:4,  name:'Ricardo Adé',          position:'DEF', club:'LDU Quito' },
      { number:8,  name:'Leverton Pierre',      position:'MID', club:'Avranches' },
      { number:14, name:'Danley Jean Jacques',  position:'MID', club:'Metz' },
      { number:9,  name:'Frantzdy Pierrot',     position:'FWD', club:'Maccabi Haifa' },
      { number:10, name:'Duckens Nazon',        position:'FWD', club:'CSKA Sofia' },
    ] },
  { flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', flagCode:'gb-sct', name:'Escocia',   slug:'escocia', coach:'Steve Clarke',         group:'C', confederation:'UEFA',
    squad:[
      { number:1,  name:'Angus Gunn',           position:'GK',  club:'Norwich City' },
      { number:3,  name:'Andy Robertson',       position:'DEF', club:'Liverpool' },
      { number:6,  name:'Kieran Tierney',       position:'DEF', club:'Real Sociedad' },
      { number:4,  name:'Scott McTominay',      position:'MID', club:'Napoli' },
      { number:7,  name:'John McGinn',          position:'MID', club:'Aston Villa' },
      { number:10, name:'Che Adams',            position:'FWD', club:'Torino' },
      { number:9,  name:'Lawrence Shankland',    position:'FWD', club:'Hearts' },
    ] },
  { flag:'🇺🇸', flagCode:'us', name:'Estados Unidos',  slug:'estados-unidos', coach:'Mauricio Pochettino',  group:'D', confederation:'CONCACAF',
    squad:[
      { number:1,  name:'Matt Turner',          position:'GK',  club:'Crystal Palace' },
      { number:5,  name:'Antonee Robinson',     position:'DEF', club:'Fulham' },
      { number:13, name:'Tim Ream',             position:'DEF', club:'Charlotte FC' },
      { number:8,  name:'Weston McKennie',      position:'MID', club:'Juventus' },
      { number:11, name:'Christian Pulisic',    position:'MID', club:'AC Milan' },
      { number:20, name:'Folarin Balogun',      position:'FWD', club:'Monaco' },
      { number:9,  name:'Ricardo Pepi',         position:'FWD', club:'PSV Eindhoven' },
    ] },
  { flag:'🇵🇾', flagCode:'py', name:'Paraguay',        slug:'paraguay', coach:'Gustavo Alfaro',        group:'D', confederation:'CONMEBOL',
    squad:[
      { number:1,  name:'Gatito Fernández',     position:'GK',  club:'Botafogo' },
      { number:4,  name:'Gustavo Gómez',        position:'DEF', club:'Palmeiras' },
      { number:3,  name:'Omar Alderete',        position:'DEF', club:'Getafe' },
      { number:8,  name:'Diego Gómez',          position:'MID', club:'Inter Miami' },
      { number:10, name:'Matías Rojas',         position:'MID', club:'Inter Miami' },
      { number:19, name:'Julio Enciso',         position:'FWD', club:'Brighton' },
      { number:10, name:'Miguel Almirón',       position:'FWD', club:'Newcastle' },
    ] },
  { flag:'🇦🇺', flagCode:'au', name:'Australia',       slug:'australia', coach:'Tony Popovic',       group:'D', confederation:'AFC',
    squad:[
      { number:1,  name:'Mat Ryan',             position:'GK',  club:'Roma' },
      { number:19, name:'Harry Souttar',        position:'DEF', club:'Sheffield United' },
      { number:4,  name:'Kye Rowles',           position:'DEF', club:'Hearts' },
      { number:22, name:'Jackson Irvine',       position:'MID', club:'St. Pauli' },
      { number:6,  name:'Keanu Baccus',         position:'MID', club:'Mansfield Town' },
      { number:23, name:'Craig Goodwin',        position:'FWD', club:'Al-Wehda' },
      { number:11, name:'Nestory Irankunda',    position:'FWD', club:'Bayern Múnich' },
    ] },
  { flag:'🇹🇷', flagCode:'tr', name:'Turquía',         slug:'turquia', coach:'Vincenzo Montella',         group:'D', confederation:'UEFA',
    squad:[
      { number:1,  name:'Mert Günok',           position:'GK',  club:'Beşiktaş' },
      { number:3,  name:'Merih Demiral',        position:'DEF', club:'Al-Ahli' },
      { number:18, name:'Ferdi Kadıoğlu',       position:'DEF', club:'Brighton' },
      { number:10, name:'Hakan Çalhanoğlu',     position:'MID', club:'Inter Milan' },
      { number:8,  name:'Arda Güler',           position:'MID', club:'Real Madrid' },
      { number:19, name:'Kenan Yıldız',         position:'FWD', club:'Juventus' },
      { number:7,  name:'Kerem Aktürkoğlu',     position:'FWD', club:'Benfica' },
    ] },
  { flag:'🇩🇪', flagCode:'de', name:'Alemania',        slug:'alemania', coach:'Julian Nagelsmann',        group:'E', confederation:'UEFA',
    squad:[
      { number:1,  name:'Marc-André ter Stegen', position:'GK', club:'Barcelona' },
      { number:2,  name:'Antonio Rüdiger',      position:'DEF', club:'Real Madrid' },
      { number:6,  name:'Joshua Kimmich',       position:'DEF', club:'Bayern Múnich' },
      { number:17, name:'Florian Wirtz',        position:'MID', club:'Bayer Leverkusen' },
      { number:10, name:'Jamal Musiala',        position:'MID', club:'Bayern Múnich' },
      { number:7,  name:'Kai Havertz',          position:'FWD', club:'Arsenal' },
      { number:9,  name:'Niclas Füllkrug',      position:'FWD', club:'West Ham' },
    ] },
  { flag:'🇨🇼', flagCode:'cw', name:'Curazao',         slug:'curazao', coach:'Remko Bicentini',         group:'E', confederation:'CONCACAF',
    squad:[
      { number:1,  name:'Eloy Room',            position:'GK',  club:'Vitesse' },
      { number:2,  name:'Cuco Martina',         position:'DEF', club:'NAC Breda' },
      { number:5,  name:'Sherel Floranus',      position:'DEF', club:'Almere City' },
      { number:8,  name:'Leandro Bacuna',       position:'MID', club:'Groningen' },
      { number:10, name:'Juninho Bacuna',       position:'MID', club:'Birmingham City' },
      { number:9,  name:'Rangelo Janga',        position:'FWD', club:'Bnei Sakhnin' },
      { number:11, name:'Kenji Gorré',          position:'FWD', club:'Umm Salal' },
    ] },
  { flag:'🇨🇮', flagCode:'ci', name:'Costa de Marfil', slug:'costa-de-marfil', coach:'Emerse Faé', group:'E', confederation:'CAF',
    squad:[
      { number:1,  name:'Yahia Fofana',         position:'GK',  club:'Angers' },
      { number:21, name:'Evan Ndicka',          position:'DEF', club:'Roma' },
      { number:5,  name:'Odilon Kossounou',     position:'DEF', club:'Atalanta' },
      { number:8,  name:'Franck Kessié',        position:'MID', club:'Al-Ahli' },
      { number:6,  name:'Seko Fofana',          position:'MID', club:'Al-Ettifaq' },
      { number:22, name:'Sébastien Haller',     position:'FWD', club:'Leganés' },
      { number:24, name:'Simon Adingra',        position:'FWD', club:'Brighton' },
    ] },
  { flag:'🇪🇨', flagCode:'ec', name:'Ecuador',         slug:'ecuador', coach:'Sebastián Beccacece',         group:'E', confederation:'CONMEBOL',
    squad:[
      { number:1,  name:'Hernán Galíndez',      position:'GK',  club:'Huracán' },
      { number:3,  name:'Piero Hincapié',       position:'DEF', club:'Bayer Leverkusen' },
      { number:6,  name:'Pervis Estupiñán',     position:'DEF', club:'Brighton' },
      { number:23, name:'Moisés Caicedo',       position:'MID', club:'Chelsea' },
      { number:10, name:'Kendry Páez',          position:'MID', club:'Independiente del Valle' },
      { number:13, name:'Enner Valencia',       position:'FWD', club:'Internacional' },
      { number:11, name:'Kevin Rodríguez',      position:'FWD', club:'Union Saint-Gilloise' },
    ] },
  { flag:'🇳🇱', flagCode:'nl', name:'Países Bajos',    slug:'paises-bajos', coach:'Ronald Koeman',    group:'F', confederation:'UEFA',
    squad:[
      { number:1,  name:'Bart Verbruggen',      position:'GK',  club:'Brighton' },
      { number:4,  name:'Virgil van Dijk',      position:'DEF', club:'Liverpool' },
      { number:5,  name:'Nathan Aké',           position:'DEF', club:'Manchester City' },
      { number:14, name:'Tijjani Reijnders',    position:'MID', club:'AC Milan' },
      { number:7,  name:'Xavi Simons',          position:'MID', club:'RB Leipzig' },
      { number:11, name:'Cody Gakpo',           position:'FWD', club:'Liverpool' },
      { number:10, name:'Memphis Depay',        position:'FWD', club:'Corinthians' },
    ] },
  { flag:'🇯🇵', flagCode:'jp', name:'Japón',           slug:'japon', coach:'Hajime Moriyasu',           group:'F', confederation:'AFC',
    squad:[
      { number:1,  name:'Zion Suzuki',          position:'GK',  club:'Parma' },
      { number:4,  name:'Ko Itakura',           position:'DEF', club:'Borussia M\'gladbach' },
      { number:2,  name:'Yukinari Sugawara',    position:'DEF', club:'Southampton' },
      { number:6,  name:'Wataru Endo',          position:'MID', club:'Liverpool' },
      { number:20, name:'Takefusa Kubo',        position:'MID', club:'Real Sociedad' },
      { number:7,  name:'Kaoru Mitoma',         position:'FWD', club:'Brighton' },
      { number:8,  name:'Takumi Minamino',      position:'FWD', club:'Monaco' },
    ] },
  { flag:'🇸🇪', flagCode:'se', name:'Suecia',          slug:'suecia', coach:'Jon Dahl Tomasson',          group:'F', confederation:'UEFA',
    squad:[
      { number:1,  name:'Robin Olsen',          position:'GK',  club:'Aston Villa' },
      { number:3,  name:'Victor Lindelöf',      position:'DEF', club:'Manchester United' },
      { number:4,  name:'Isak Hien',            position:'DEF', club:'Atalanta' },
      { number:21, name:'Dejan Kulusevski',     position:'MID', club:'Tottenham' },
      { number:16, name:'Hugo Larsson',         position:'MID', club:'Eintracht Frankfurt' },
      { number:17, name:'Viktor Gyökeres',      position:'FWD', club:'Sporting CP' },
      { number:9,  name:'Alexander Isak',       position:'FWD', club:'Newcastle' },
    ] },
  { flag:'🇹🇳', flagCode:'tn', name:'Túnez',           slug:'tunez', coach:'Faouzi Benzarti',           group:'F', confederation:'CAF',
    squad:[
      { number:1,  name:'Bechir Ben Saïd',      position:'GK',  club:'Espérance de Tunis' },
      { number:4,  name:'Montassar Talbi',      position:'DEF', club:'Lorient' },
      { number:2,  name:'Ali Abdi',             position:'DEF', club:'Nice' },
      { number:17, name:'Ellyes Skhiri',        position:'MID', club:'Eintracht Frankfurt' },
      { number:14, name:'Aïssa Laïdouni',       position:'MID', club:'Al-Wakrah' },
      { number:7,  name:'Youssef Msakni',       position:'FWD', club:'Al-Arabi' },
      { number:11, name:'Elias Achouri',        position:'FWD', club:'Copenhagen' },
    ] },
  { flag:'🇧🇪', flagCode:'be', name:'Bélgica',         slug:'belgica', coach:'Domenico Tedesco',         group:'G', confederation:'UEFA',
    squad:[
      { number:1,  name:'Koen Casteels',        position:'GK',  club:'Al-Qadsiah' },
      { number:4,  name:'Wout Faes',            position:'DEF', club:'Leicester City' },
      { number:21, name:'Timothy Castagne',     position:'DEF', club:'Fulham' },
      { number:7,  name:'Kevin De Bruyne',      position:'MID', club:'Manchester City' },
      { number:6,  name:'Amadou Onana',         position:'MID', club:'Aston Villa' },
      { number:10, name:'Romelu Lukaku',        position:'FWD', club:'Napoli' },
      { number:11, name:'Jeremy Doku',          position:'FWD', club:'Manchester City' },
    ] },
  { flag:'🇪🇬', flagCode:'eg', name:'Egipto',          slug:'egipto', coach:'Hossam Hassan',          group:'G', confederation:'CAF',
    squad:[
      { number:1,  name:'Mohamed El Shenawy',   position:'GK',  club:'Al Ahly' },
      { number:24, name:'Mohamed Abdelmonem',   position:'DEF', club:'Nice' },
      { number:5,  name:'Rami Rabia',           position:'DEF', club:'Al Ahly' },
      { number:14, name:'Marwan Attia',         position:'MID', club:'Al Ahly' },
      { number:7,  name:'Trézéguet',            position:'MID', club:'Al-Rayyan' },
      { number:10, name:'Mohamed Salah',        position:'FWD', club:'Liverpool' },
      { number:22, name:'Omar Marmoush',        position:'FWD', club:'Eintracht Frankfurt' },
    ] },
  { flag:'🇮🇷', flagCode:'ir', name:'Irán',            slug:'iran', coach:'Cheragh Radinovic',            group:'G', confederation:'AFC',
    squad:[
      { number:1,  name:'Alireza Beiranvand',   position:'GK',  club:'Tractor' },
      { number:5,  name:'Milad Mohammadi',      position:'DEF', club:'Persepolis' },
      { number:4,  name:'Shojae Khalilzadeh',   position:'DEF', club:'Tractor' },
      { number:6,  name:'Saeid Ezatolahi',      position:'MID', club:'Shabab Al-Ahli' },
      { number:14, name:'Saman Ghoddos',        position:'MID', club:'Ittihad Kalba' },
      { number:9,  name:'Mehdi Taremi',         position:'FWD', club:'Inter Milan' },
      { number:20, name:'Sardar Azmoun',        position:'FWD', club:'Shabab Al-Ahli' },
    ] },
  { flag:'🇳🇿', flagCode:'nz', name:'Nueva Zelanda',   slug:'nueva-zelanda', coach:'Darren Bazeley',   group:'G', confederation:'OFC',
    squad:[
      { number:1,  name:'Alex Paulsen',         position:'GK',  club:'Auckland FC' },
      { number:3,  name:'Liberato Cacace',      position:'DEF', club:'Empoli' },
      { number:4,  name:'Michael Boxall',       position:'DEF', club:'Minnesota United' },
      { number:8,  name:'Marko Stamenic',       position:'MID', club:'Olympiacos' },
      { number:10, name:'Matthew Garbett',      position:'MID', club:'NAC Breda' },
      { number:9,  name:'Chris Wood',           position:'FWD', club:'Nottingham Forest' },
      { number:7,  name:'Kosta Barbarouses',    position:'FWD', club:'Wellington Phoenix' },
    ] },
  { flag:'🇪🇸', flagCode:'es', name:'España',          slug:'espana',          group:'H', confederation:'UEFA',
    worldCupBest:'Campeona del Mundo 2010 · La Roja de Xavi, Iniesta y Torres en Sudáfrica',
    coach:'Luis de la Fuente',
    squad:[
      { number:1,  name:'Unai Simón',         position:'GK',  club:'Athletic Club' },
      { number:13, name:'David Raya',          position:'GK',  club:'Arsenal' },
      { number:23, name:'Álex Remiro',         position:'GK',  club:'Real Sociedad' },
      { number:2,  name:'Dani Carvajal',       position:'DEF', club:'Real Madrid' },
      { number:3,  name:'Alejandro Balde',     position:'DEF', club:'Barcelona' },
      { number:4,  name:'Nacho Fernández',     position:'DEF', club:'Al-Qadsiah' },
      { number:5,  name:'Aymeric Laporte',     position:'DEF', club:'Al-Nassr' },
      { number:24, name:'Robin Le Normand',    position:'DEF', club:'Atlético Madrid' },
      { number:18, name:'Joselu',              position:'FWD', club:'Maccabi Tel Aviv' },
      { number:20, name:'Pedro Porro',         position:'DEF', club:'Tottenham' },
      { number:25, name:'Pau Cubarsí',         position:'DEF', club:'Barcelona' },
      { number:6,  name:'Rodrigo Hernández',   position:'MID', club:'Manchester City' },
      { number:8,  name:'Fabián Ruiz',         position:'MID', club:'PSG' },
      { number:16, name:'Martín Zubimendi',    position:'MID', club:'Arsenal' },
      { number:19, name:'Dani Olmo',           position:'MID', club:'Barcelona' },
      { number:10, name:'Pedri',               position:'MID', club:'Barcelona' },
      { number:14, name:'Mikel Merino',        position:'MID', club:'Arsenal' },
      { number:26, name:'Alex Baena',          position:'MID', club:'Villarreal' },
      { number:7,  name:'Álvaro Morata',       position:'FWD', club:'AC Milan' },
      { number:9,  name:'Ayoze Pérez',         position:'FWD', club:'Villarreal' },
      { number:11, name:'Ferran Torres',       position:'FWD', club:'Barcelona' },
      { number:17, name:'Nico Williams',       position:'FWD', club:'Athletic Club' },
      { number:21, name:'Mikel Oyarzabal',     position:'FWD', club:'Real Sociedad' },
      { number:22, name:'Bryan Gil',           position:'FWD', club:'Girona' },
      { number:12, name:'Yeremy Pino',         position:'FWD', club:'Villarreal' },
      { number:15, name:'Iñigo Martínez',      position:'DEF', club:'Barcelona' },
    ] },
  { flag:'🇨🇻', flagCode:'cv', name:'Cabo Verde',      slug:'cabo-verde', coach:'Bubista',      group:'H', confederation:'CAF',
    squad:[
      { number:1,  name:'Vozinha',              position:'GK',  club:'AS Trenčín' },
      { number:4,  name:'Logan Costa',          position:'DEF', club:'Villarreal' },
      { number:3,  name:'Pico Lopes',           position:'DEF', club:'Shamrock Rovers' },
      { number:10, name:'Jamiro Monteiro',      position:'MID', club:'Gaziantep' },
      { number:15, name:'Kevin Pina',           position:'MID', club:'Krasnodar' },
      { number:20, name:'Ryan Mendes',          position:'FWD', club:'Fatih Karagümrük' },
      { number:11, name:'Garry Rodrigues',      position:'FWD', club:'Sivasspor' },
    ] },
  { flag:'🇸🇦', flagCode:'sa', name:'Arabia Saudí',    slug:'arabia-saudi', coach:'Hervé Renard',    group:'H', confederation:'AFC',
    squad:[
      { number:1,  name:'Ahmed Al-Kassar',      position:'GK',  club:'Al-Qadsiah' },
      { number:4,  name:'Ali Lajami',           position:'DEF', club:'Al-Nassr' },
      { number:12, name:'Saud Abdulhamid',      position:'DEF', club:'Roma' },
      { number:23, name:'Mohamed Kanno',        position:'MID', club:'Al-Hilal' },
      { number:8,  name:'Musab Al-Juwayr',      position:'MID', club:'Al-Shabab' },
      { number:10, name:'Salem Al-Dawsari',     position:'FWD', club:'Al-Hilal' },
      { number:9,  name:'Firas Al-Buraikan',    position:'FWD', club:'Al-Ahli' },
    ] },
  { flag:'🇺🇾', flagCode:'uy', name:'Uruguay',         slug:'uruguay', coach:'Marcelo Bielsa',         group:'H', confederation:'CONMEBOL',
    squad:[
      { number:1,  name:'Sergio Rochet',        position:'GK',  club:'Internacional' },
      { number:4,  name:'Ronald Araújo',        position:'DEF', club:'Barcelona' },
      { number:2,  name:'José María Giménez',   position:'DEF', club:'Atlético Madrid' },
      { number:15, name:'Federico Valverde',    position:'MID', club:'Real Madrid' },
      { number:6,  name:'Rodrigo Bentancur',    position:'MID', club:'Tottenham' },
      { number:19, name:'Darwin Núñez',         position:'FWD', club:'Liverpool' },
      { number:9,  name:'Luis Suárez',          position:'FWD', club:'Inter Miami' },
    ] },
  { flag:'🇫🇷', flagCode:'fr', name:'Francia',         slug:'francia',         group:'I', confederation:'UEFA',
    worldCupBest:'Campeona del Mundo 1998 y 2018 · Finalista en Qatar 2022',
    coach:'Didier Deschamps',
    squad:[
      { number:1,  name:'Mike Maignan',          position:'GK',  club:'AC Milan' },
      { number:16, name:'Alphonse Areola',        position:'GK',  club:'West Ham' },
      { number:23, name:'Brice Samba',            position:'GK',  club:'Lens' },
      { number:2,  name:'Benjamin Pavard',        position:'DEF', club:'Inter Milán' },
      { number:5,  name:'Jules Koundé',           position:'DEF', club:'Barcelona' },
      { number:21, name:'Lucas Hernández',        position:'DEF', club:'PSG' },
      { number:22, name:'Théo Hernández',         position:'DEF', club:'AC Milan' },
      { number:4,  name:'Dayot Upamecano',        position:'DEF', club:'Bayern Múnich' },
      { number:3,  name:'Ferland Mendy',          position:'DEF', club:'Real Madrid' },
      { number:24, name:'Jonathan Clauss',        position:'DEF', club:'Marsella' },
      { number:15, name:'Ibrahima Konaté',        position:'DEF', club:'Liverpool' },
      { number:25, name:'William Saliba',         position:'DEF', club:'Arsenal' },
      { number:6,  name:'Eduardo Camavinga',      position:'MID', club:'Real Madrid' },
      { number:8,  name:'Aurélien Tchouaméni',    position:'MID', club:'Real Madrid' },
      { number:14, name:'Adrien Rabiot',          position:'MID', club:'Marsella' },
      { number:13, name:"N'Golo Kanté",          position:"MID", club:"Al-Ittihad" },
      { number:18, name:'Mattéo Guendouzi',       position:'MID', club:'Lazio' },
      { number:19, name:'Youssouf Fofana',        position:'MID', club:'AC Milan' },
      { number:26, name:'Warren Zaïre-Emery',     position:'MID', club:'PSG' },
      { number:10, name:'Kylian Mbappé',          position:'FWD', club:'Real Madrid' },
      { number:7,  name:'Antoine Griezmann',      position:'FWD', club:'Atlético Madrid' },
      { number:11, name:'Ousmane Dembélé',        position:'FWD', club:'PSG' },
      { number:9,  name:'Olivier Giroud',         position:'FWD', club:'LA Galaxy' },
      { number:17, name:'Marcus Thuram',          position:'FWD', club:'Inter Milán' },
      { number:20, name:'Bradley Barcola',        position:'FWD', club:'PSG' },
      { number:12, name:'Randal Kolo Muani',      position:'FWD', club:'Juventus' },
    ] },
  { flag:'🇸🇳', flagCode:'sn', name:'Senegal',         slug:'senegal', coach:'Aliou Cissé',         group:'I', confederation:'CAF',
    squad:[
      { number:16, name:'Édouard Mendy',        position:'GK',  club:'Al-Ahli' },
      { number:3,  name:'Kalidou Koulibaly',    position:'DEF', club:'Al-Hilal' },
      { number:22, name:'Abdou Diallo',         position:'DEF', club:'Al-Arabi' },
      { number:5,  name:'Idrissa Gueye',        position:'MID', club:'Everton' },
      { number:15, name:'Krépin Diatta',        position:'MID', club:'Monaco' },
      { number:10, name:'Sadio Mané',           position:'FWD', club:'Al-Nassr' },
      { number:18, name:'Ismaïla Sarr',         position:'FWD', club:'Crystal Palace' },
    ] },
  { flag:'🇮🇶', flagCode:'iq', name:'Irak',            slug:'irak', coach:'Jesus Casas',            group:'I', confederation:'AFC',
    squad:[
      { number:12, name:'Jalal Hassan',         position:'GK',  club:'Al-Zawraa' },
      { number:4,  name:'Saad Natiq',           position:'DEF', club:'Al-Quwa Al-Jawiya' },
      { number:3,  name:'Rebin Sulaka',         position:'DEF', club:'Seraing' },
      { number:8,  name:'Ibrahim Bayesh',       position:'MID', club:'Al-Quwa Al-Jawiya' },
      { number:17, name:'Ali Jasim',            position:'MID', club:'Como' },
      { number:18, name:'Aymen Hussein',        position:'FWD', club:'Al-Khor' },
      { number:10, name:'Mohanad Ali',          position:'FWD', club:'Al-Shorta' },
    ] },
  { flag:'🇳🇴', flagCode:'no', name:'Noruega',         slug:'noruega', coach:'Ståle Solbakken',         group:'I', confederation:'UEFA',
    squad:[
      { number:1,  name:'Ørjan Nyland',         position:'GK',  club:'Sevilla' },
      { number:4,  name:'Leo Østigård',         position:'DEF', club:'Rennes' },
      { number:3,  name:'Kristoffer Ajer',      position:'DEF', club:'Brentford' },
      { number:8,  name:'Martin Ødegaard',      position:'MID', club:'Arsenal' },
      { number:10, name:'Sander Berge',         position:'MID', club:'Fulham' },
      { number:9,  name:'Erling Haaland',       position:'FWD', club:'Manchester City' },
      { number:19, name:'Alexander Sørloth',    position:'FWD', club:'Atlético Madrid' },
    ] },
  { flag:'🇦🇷', flagCode:'ar', name:'Argentina',       slug:'argentina',       group:'J', confederation:'CONMEBOL', isChampion:true,
    description:'Campeona del mundo en Qatar 2022 bajo la conducción de Lionel Scaloni. Busca defender el título con Lionel Messi como figura central.',
    worldCupBest:'Campeona del Mundo 1978, 1986 y 2022 · Tres estrellas en la camiseta albiceleste',
    coach:'Lionel Scaloni',
    squad:[
      { number:23, name:'Emiliano Martínez',   position:'GK',  club:'Aston Villa' },
      { number:12, name:'Geronimo Rulli',       position:'GK',  club:'Villarreal' },
      { number:1,  name:'Franco Armani',        position:'GK',  club:'River Plate' },
      { number:4,  name:'Gonzalo Montiel',      position:'DEF', club:'Nottingham Forest' },
      { number:26, name:'Nahuel Molina',        position:'DEF', club:'Atlético Madrid' },
      { number:13, name:'Cristian Romero',      position:'DEF', club:'Tottenham' },
      { number:19, name:'Nicolás Otamendi',     position:'DEF', club:'Benfica' },
      { number:6,  name:'Germán Pezzella',      position:'DEF', club:'Real Betis' },
      { number:3,  name:'Nicolás Tagliafico',   position:'DEF', club:'Lyon' },
      { number:2,  name:'Juan Foyth',           position:'DEF', club:'Villarreal' },
      { number:8,  name:'Marcos Acuña',         position:'DEF', club:'Sporting CP' },
      { number:25, name:'Lisandro Martínez',    position:'DEF', club:'Manchester United' },
      { number:7,  name:'Rodrigo De Paul',      position:'MID', club:'Atlético Madrid' },
      { number:5,  name:'Leandro Paredes',      position:'MID', club:'Roma' },
      { number:14, name:'Enzo Fernández',       position:'MID', club:'Chelsea' },
      { number:20, name:'Alexis Mac Allister',  position:'MID', club:'Liverpool' },
      { number:16, name:'Thiago Almada',        position:'MID', club:'Lyon' },
      { number:17, name:'Giovani Lo Celso',     position:'MID', club:'Villarreal' },
      { number:18, name:'Guido Rodríguez',      position:'MID', club:'Real Betis' },
      { number:24, name:'Exequiel Palacios',    position:'MID', club:'Bayer Leverkusen' },
      { number:15, name:'Nicolás González',     position:'MID', club:'Juventus' },
      { number:11, name:'Ángel Di María',       position:'FWD', club:'Benfica' },
      { number:22, name:'Lautaro Martínez',     position:'FWD', club:'Inter Milán' },
      { number:10, name:'Lionel Messi',         position:'FWD', club:'Inter Miami' },
      { number:9,  name:'Julián Álvarez',       position:'FWD', club:'Atlético Madrid' },
      { number:21, name:'Paulo Dybala',         position:'FWD', club:'Roma' },
    ] },
  { flag:'🇩🇿', flagCode:'dz', name:'Argelia',         slug:'argelia', coach:'Vladimir Petkovic',         group:'J', confederation:'CAF',
    squad:[
      { number:1,  name:'Anthony Mandrea',      position:'GK',  club:'Caen' },
      { number:3,  name:'Rayan Aït-Nouri',      position:'DEF', club:'Wolverhampton' },
      { number:2,  name:'Aïssa Mandi',          position:'DEF', club:'Lille' },
      { number:6,  name:'Ramiz Zerrouki',       position:'MID', club:'Feyenoord' },
      { number:10, name:'Saïd Benrahma',        position:'MID', club:'Lyon' },
      { number:7,  name:'Riyad Mahrez',         position:'FWD', club:'Al-Ahli' },
      { number:9,  name:'Baghdad Bounedjah',    position:'FWD', club:'Al-Shamal' },
    ] },
  { flag:'🇦🇹', flagCode:'at', name:'Austria',         slug:'austria', coach:'Ralf Rangnick',         group:'J', confederation:'UEFA',
    squad:[
      { number:1,  name:'Alexander Schlager',   position:'GK',  club:'Red Bull Salzburg' },
      { number:3,  name:'Stefan Posch',         position:'DEF', club:'Bologna' },
      { number:2,  name:'Maximilian Wöber',     position:'DEF', club:'Leeds United' },
      { number:9,  name:'Marcel Sabitzer',      position:'MID', club:'Borussia Dortmund' },
      { number:19, name:'Christoph Baumgartner', position:'MID', club:'RB Leipzig' },
      { number:11, name:'Michael Gregoritsch',  position:'FWD', club:'Freiburg' },
      { number:7,  name:'Marko Arnautović',     position:'FWD', club:'Inter Milan' },
    ] },
  { flag:'🇯🇴', flagCode:'jo', name:'Jordania',        slug:'jordania', coach:'Hussam Abu Jawad',        group:'J', confederation:'AFC',
    squad:[
      { number:1,  name:'Yazeed Abulaila',      position:'GK',  club:'Al-Hussein' },
      { number:3,  name:'Yazan Al-Arab',        position:'DEF', club:'FC Seoul' },
      { number:2,  name:'Abdallah Nasib',       position:'DEF', club:'Al-Hussein' },
      { number:10, name:'Musa Al-Taamari',      position:'MID', club:'Montpellier' },
      { number:8,  name:'Noor Al-Rawabdeh',     position:'MID', club:'Selangor' },
      { number:11, name:'Yazan Al-Naimat',      position:'FWD', club:'Al-Arabi' },
      { number:9,  name:'Ali Olwan',            position:'FWD', club:'Selangor' },
    ] },
  { flag:'🇵🇹', flagCode:'pt', name:'Portugal',        slug:'portugal', coach:'Roberto Martínez',        group:'K', confederation:'UEFA',
    squad:[
      { number:1,  name:'Diogo Costa',          position:'GK',  club:'Porto' },
      { number:3,  name:'Rúben Dias',           position:'DEF', club:'Manchester City' },
      { number:20, name:'João Cancelo',         position:'DEF', club:'Al-Hilal' },
      { number:8,  name:'Bruno Fernandes',      position:'MID', club:'Manchester United' },
      { number:10, name:'Bernardo Silva',       position:'MID', club:'Manchester City' },
      { number:7,  name:'Cristiano Ronaldo',    position:'FWD', club:'Al-Nassr' },
      { number:17, name:'Rafael Leão',          position:'FWD', club:'AC Milan' },
    ] },
  { flag:'🇨🇩', flagCode:'cd', name:'RD Congo',        slug:'rd-congo', coach:'Sébastien Desabre',        group:'K', confederation:'CAF',
    squad:[
      { number:1,  name:'Lionel Mpasi',         position:'GK',  club:'Rodez' },
      { number:22, name:'Chancel Mbemba',       position:'DEF', club:'Marseille' },
      { number:2,  name:'Henoc Inonga',         position:'DEF', club:'FAR Rabat' },
      { number:8,  name:'Samuel Moutoussamy',   position:'MID', club:'Sivasspor' },
      { number:10, name:'Theo Bongonda',        position:'MID', club:'Spartak Moscú' },
      { number:17, name:'Cédric Bakambu',       position:'FWD', club:'Betis' },
      { number:19, name:'Yoane Wissa',          position:'FWD', club:'Brentford' },
    ] },
  { flag:'🇨🇴', flagCode:'co', name:'Colombia',        slug:'colombia', coach:'Néstor Lorenzo',        group:'K', confederation:'CONMEBOL',
    squad:[
      { number:12, name:'Camilo Vargas',        position:'GK',  club:'Atlas' },
      { number:23, name:'Davinson Sánchez',     position:'DEF', club:'Galatasaray' },
      { number:2,  name:'Daniel Muñoz',         position:'DEF', club:'Crystal Palace' },
      { number:10, name:'James Rodríguez',      position:'MID', club:'Rayo Vallecano' },
      { number:6,  name:'Richard Ríos',         position:'MID', club:'Palmeiras' },
      { number:7,  name:'Luis Díaz',            position:'FWD', club:'Liverpool' },
      { number:19, name:'Jhon Durán',           position:'FWD', club:'Aston Villa' },
    ] },
  { flag:'🇺🇿', flagCode:'uz', name:'Uzbekistán',      slug:'uzbekistan', coach:'Srecko Katanec',      group:'K', confederation:'AFC',
    squad:[
      { number:1,  name:'Utkir Yusupov',        position:'GK',  club:'Foolad' },
      { number:15, name:'Umar Eshmurodov',      position:'DEF', club:'Selangor' },
      { number:4,  name:'Husniddin Aliqulov',   position:'DEF', club:'Çaykur Rizespor' },
      { number:9,  name:'Odiljon Hamrobekov',   position:'MID', club:'Navbahor' },
      { number:10, name:'Jaloliddin Masharipov', position:'MID', club:'Esteghlal' },
      { number:14, name:'Eldor Shomurodov',     position:'FWD', club:'Roma' },
      { number:11, name:'Oston Urunov',         position:'FWD', club:'Persepolis' },
    ] },
  { flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', flagCode:'gb-eng', name:'Inglaterra', slug:'inglaterra', coach:'Thomas Tuchel',    group:'L', confederation:'UEFA',
    squad:[
      { number:1,  name:'Jordan Pickford',      position:'GK',  club:'Everton' },
      { number:5,  name:'John Stones',          position:'DEF', club:'Manchester City' },
      { number:6,  name:'Marc Guéhi',           position:'DEF', club:'Crystal Palace' },
      { number:4,  name:'Declan Rice',          position:'MID', club:'Arsenal' },
      { number:10, name:'Jude Bellingham',      position:'MID', club:'Real Madrid' },
      { number:9,  name:'Harry Kane',           position:'FWD', club:'Bayern Múnich' },
      { number:7,  name:'Bukayo Saka',          position:'FWD', club:'Arsenal' },
    ] },
  { flag:'🇭🇷', flagCode:'hr', name:'Croacia',         slug:'croacia', coach:'Zlatko Dalic',         group:'L', confederation:'UEFA',
    squad:[
      { number:1,  name:'Dominik Livaković',    position:'GK',  club:'Fenerbahçe' },
      { number:4,  name:'Joško Gvardiol',       position:'DEF', club:'Manchester City' },
      { number:6,  name:'Duje Ćaleta-Car',      position:'DEF', club:'Lyon' },
      { number:10, name:'Luka Modrić',          position:'MID', club:'Real Madrid' },
      { number:8,  name:'Mateo Kovačić',        position:'MID', club:'Manchester City' },
      { number:9,  name:'Andrej Kramarić',      position:'FWD', club:'Hoffenheim' },
      { number:14, name:'Ivan Perišić',         position:'FWD', club:'Hajduk Split' },
    ] },
  { flag:'🇬🇭', flagCode:'gh', name:'Ghana',           slug:'ghana', coach:'Otto Addo',           group:'L', confederation:'CAF',
    squad:[
      { number:1,  name:'Lawrence Ati-Zigi',    position:'GK',  club:'St. Gallen' },
      { number:15, name:'Alidu Seidu',          position:'DEF', club:'Rennes' },
      { number:22, name:'Mohammed Salisu',      position:'DEF', club:'Monaco' },
      { number:5,  name:'Thomas Partey',        position:'MID', club:'Arsenal' },
      { number:20, name:'Mohammed Kudus',       position:'MID', club:'West Ham' },
      { number:9,  name:'Jordan Ayew',          position:'FWD', club:'Leicester City' },
      { number:19, name:'Iñaki Williams',       position:'FWD', club:'Athletic Club' },
    ] },
  { flag:'🇵🇦', flagCode:'pa', name:'Panamá',          slug:'panama', coach:'Thomas Christiansen',          group:'L', confederation:'CONCACAF',
    squad:[
      { number:22, name:'Orlando Mosquera',     position:'GK',  club:'Al-Fayha' },
      { number:3,  name:'José Córdoba',         position:'DEF', club:'Norwich City' },
      { number:4,  name:'Eduardo Anderson',     position:'DEF', club:'Saprissa' },
      { number:8,  name:'Adalberto Carrasquilla', position:'MID', club:'Houston Dynamo' },
      { number:6,  name:'Cristian Martínez',    position:'MID', club:'Kortrijk' },
      { number:17, name:'José Fajardo',         position:'FWD', club:'Universidad Católica' },
      { number:10, name:'Ismael Díaz',          position:'FWD', club:'Universidad Católica' },
    ] },
]

export const TEAMS_BY_SLUG = Object.fromEntries(TEAMS.map(t => [t.slug, t]))
export const TEAMS_BY_NAME = Object.fromEntries(TEAMS.map(t => [t.name, t]))

// ─── GRUPOS ──────────────────────────────────────────────────────────────────

export const GROUPS: Group[] = 'ABCDEFGHIJKL'.split('').map(letter => ({
  letter,
  teams: TEAMS.filter(t => t.group === letter).map(t => ({
    flag: t.flag, flagCode: t.flagCode, name: t.name, slug: t.slug,
  })),
}))

// ─── DERIVACIÓN DE FECHA DESDE KICKOFF (Opción A) ────────────────────────────
// `date` y `dateSort` ya NO se escriben a mano. Se calculan siempre a partir
// de `kickoff` (UTC), que es la única fuente de verdad. Esto elimina la clase
// de bug donde `date` y `kickoff` quedaban desincronizados entre sí.
//
// `date` se muestra en formato "11 jun" usando la fecha UTC (no la local del
// usuario): es solo un label de fallback para mientras el cliente hidrata;
// la hora/fecha real que ve el usuario la calcula MatchTime.tsx con Intl API.

const MESES_ES = ['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic']

function deriveDateFields(kickoffISO: string): { date: string; dateSort: number } {
  const d = new Date(kickoffISO)
  const year  = d.getUTCFullYear()
  const month = d.getUTCMonth() // 0-indexed
  const day   = d.getUTCDate()

  const date = `${day} ${MESES_ES[month]}`
  const dateSort = year * 10000 + (month + 1) * 100 + day  // ej: 20260611

  return { date, dateSort }
}

interface RawMatch {
  id: string
  kickoff: string   // ISO 8601 UTC — única fuente de verdad temporal
  group: string
  home: string       // nombre del equipo (se resuelve con makeRef)
  away: string
  venue: string
  stadium?: string
  city: string
  isArgentina?: boolean
}

function makeRef(name: string): import('@/types').TeamRef {
  const t = TEAMS.find(x => x.name === name)!
  if (!t) throw new Error(`makeRef: equipo no encontrado "${name}"`)
  return { flag: t.flag, flagCode: t.flagCode, name: t.name, slug: t.slug }
}

function buildMatch(raw: RawMatch): Match {
  const { date, dateSort } = deriveDateFields(raw.kickoff)
  return {
    id: raw.id,
    date,
    dateSort,
    kickoff: raw.kickoff,
    group: raw.group,
    home: makeRef(raw.home),
    away: makeRef(raw.away),
    venue: raw.venue,
    stadium: raw.stadium,
    city: raw.city,
    isArgentina: raw.isArgentina,
    status: 'pending',
  }
}

// ─── PARTIDOS — DATOS CRUDOS ──────────────────────────────────────────────────
// Los 66 kickoffs marcados [CORREGIDO] fueron reemplazados por el horario
// oficial real verificado contra el calendario ET publicado (worldcupwiki.com,
// ESPN, CBS Sports, Sky Sports — cruzados entre sí) y convertidos a UTC
// (ET de junio = UTC-4, horario de verano EDT).
//
// Los partidos de Eslovenia (K2, K4b, K6) fueron reemplazados por los de
// Uzbekistán, el equipo real del Grupo K.

const RAW_MATCHES: RawMatch[] = [
  // ════════════════════════════════════════════
  // FECHA 1  (11–17 jun)
  // ════════════════════════════════════════════
  { id:'A1', kickoff:'2026-06-11T19:00:00Z', group:'A', home:'México', away:'Sudáfrica',
    venue:'Ciudad de México', stadium:'Estadio Azteca', city:'Ciudad de México' },
  { id:'A2', kickoff:'2026-06-11T22:00:00Z', group:'A', home:'Corea del Sur', away:'Rep. Checa',
    venue:'Zapopan', stadium:'Estadio Akron', city:'Zapopan' },

  { id:'B1', kickoff:'2026-06-12T19:00:00Z', group:'B', home:'Canadá', away:'Bosnia y Herz.',
    venue:'Toronto', stadium:'BMO Field', city:'Toronto' },
  { id:'D1', kickoff:'2026-06-12T22:00:00Z', group:'D', home:'Estados Unidos', away:'Paraguay',
    venue:'Los Ángeles', stadium:'SoFi Stadium', city:'Inglewood' },
  { id:'D2', kickoff:'2026-06-14T01:00:00Z', group:'D', home:'Australia', away:'Turquía',
    venue:'Vancouver', stadium:'BC Place', city:'Vancouver' },

  { id:'B2', kickoff:'2026-06-13T16:00:00Z', group:'B', home:'Qatar', away:'Suiza',
    venue:'Santa Clara', stadium:"Levi's Stadium", city:'Santa Clara' },
  { id:'C1', kickoff:'2026-06-13T19:00:00Z', group:'C', home:'Brasil', away:'Marruecos',
    venue:'Nueva York/NJ', stadium:'MetLife Stadium', city:'East Rutherford' },
  { id:'C2', kickoff:'2026-06-13T22:00:00Z', group:'C', home:'Haití', away:'Escocia',
    venue:'Boston', stadium:'Gillette Stadium', city:'Foxborough' },

  { id:'E1', kickoff:'2026-06-14T16:00:00Z', group:'E', home:'Alemania', away:'Curazao',
    venue:'Houston', stadium:'NRG Stadium', city:'Houston' },
  { id:'F1', kickoff:'2026-06-14T19:00:00Z', group:'F', home:'Países Bajos', away:'Japón',
    venue:'Dallas', stadium:'AT&T Stadium', city:'Arlington' },
  { id:'E2', kickoff:'2026-06-14T22:00:00Z', group:'E', home:'Costa de Marfil', away:'Ecuador',
    venue:'Filadelfia', stadium:'Lincoln Financial Field', city:'Filadelfia' },
  { id:'F2', kickoff:'2026-06-15T01:00:00Z', group:'F', home:'Suecia', away:'Túnez',
    venue:'Monterrey', stadium:'Estadio BBVA', city:'Monterrey' },

  { id:'H1', kickoff:'2026-06-15T16:00:00Z', group:'H', home:'España', away:'Cabo Verde',
    venue:'Atlanta', stadium:'Mercedes-Benz Stadium', city:'Atlanta' },
  { id:'G1', kickoff:'2026-06-15T19:00:00Z', group:'G', home:'Bélgica', away:'Egipto',
    venue:'Seattle', stadium:'Lumen Field', city:'Seattle' },
  { id:'H2', kickoff:'2026-06-15T22:00:00Z', group:'H', home:'Arabia Saudí', away:'Uruguay',
    venue:'Miami', stadium:'Hard Rock Stadium', city:'Miami Gardens' },
  { id:'G2', kickoff:'2026-06-16T01:00:00Z', group:'G', home:'Irán', away:'Nueva Zelanda',
    venue:'Los Ángeles', stadium:'SoFi Stadium', city:'Inglewood' },

  { id:'I1', kickoff:'2026-06-16T19:00:00Z', group:'I', home:'Francia', away:'Senegal',
    venue:'Nueva York/NJ', stadium:'MetLife Stadium', city:'East Rutherford' },
  { id:'I2', kickoff:'2026-06-16T22:00:00Z', group:'I', home:'Irak', away:'Noruega',
    venue:'Boston', stadium:'Gillette Stadium', city:'Foxborough' },
  { id:'J1', kickoff:'2026-06-17T01:00:00Z', group:'J', home:'Argentina', away:'Argelia',
    venue:'Kansas City', stadium:'Arrowhead Stadium', city:'Kansas City', isArgentina:true },

  { id:'J2', kickoff:'2026-06-17T04:00:00Z', group:'J', home:'Austria', away:'Jordania',
    venue:'San Francisco', stadium:"Levi's Stadium", city:'Santa Clara' },
  { id:'K1', kickoff:'2026-06-17T17:00:00Z', group:'K', home:'Portugal', away:'RD Congo',
    venue:'Houston', stadium:'NRG Stadium', city:'Houston' },
  { id:'L1', kickoff:'2026-06-17T20:00:00Z', group:'L', home:'Inglaterra', away:'Croacia',
    venue:'Dallas', stadium:'AT&T Stadium', city:'Arlington' },
  { id:'L2', kickoff:'2026-06-17T23:00:00Z', group:'L', home:'Ghana', away:'Panamá',
    venue:'Toronto', stadium:'BMO Field', city:'Toronto' },
  { id:'K2', kickoff:'2026-06-18T02:00:00Z', group:'K', home:'Uzbekistán', away:'Colombia',
    venue:'Ciudad de México', stadium:'Estadio Azteca', city:'Ciudad de México' },

  // ════════════════════════════════════════════
  // FECHA 2  (18–23 jun)
  // ════════════════════════════════════════════
  { id:'A3', kickoff:'2026-06-18T16:00:00Z', group:'A', home:'Rep. Checa', away:'Sudáfrica',
    venue:'Atlanta', stadium:'Mercedes-Benz Stadium', city:'Atlanta' },
  { id:'B3', kickoff:'2026-06-18T19:00:00Z', group:'B', home:'Suiza', away:'Bosnia y Herz.',
    venue:'Los Ángeles', stadium:'SoFi Stadium', city:'Inglewood' },
  { id:'B4', kickoff:'2026-06-18T22:00:00Z', group:'B', home:'Canadá', away:'Qatar',
    venue:'Vancouver', stadium:'BC Place', city:'Vancouver' },
  { id:'A4', kickoff:'2026-06-19T01:00:00Z', group:'A', home:'México', away:'Corea del Sur',
    venue:'Zapopan', stadium:'Estadio Akron', city:'Zapopan' },

  { id:'D3', kickoff:'2026-06-19T19:00:00Z', group:'D', home:'Estados Unidos', away:'Australia',
    venue:'Seattle', stadium:'Lumen Field', city:'Seattle' },
  { id:'C3', kickoff:'2026-06-19T22:00:00Z', group:'C', home:'Escocia', away:'Marruecos',
    venue:'Boston', stadium:'Gillette Stadium', city:'Foxborough' },
  { id:'C4', kickoff:'2026-06-20T00:30:00Z', group:'C', home:'Brasil', away:'Haití',
    venue:'Filadelfia', stadium:'Lincoln Financial Field', city:'Filadelfia' },
  { id:'D4', kickoff:'2026-06-20T03:00:00Z', group:'D', home:'Turquía', away:'Paraguay',
    venue:'Santa Clara', stadium:"Levi's Stadium", city:'Santa Clara' },

  { id:'F3', kickoff:'2026-06-20T17:00:00Z', group:'F', home:'Países Bajos', away:'Suecia',
    venue:'Houston', stadium:'NRG Stadium', city:'Houston' },
  { id:'E3', kickoff:'2026-06-20T20:00:00Z', group:'E', home:'Alemania', away:'Costa de Marfil',
    venue:'Toronto', stadium:'BMO Field', city:'Toronto' },
  { id:'E4', kickoff:'2026-06-21T00:00:00Z', group:'E', home:'Ecuador', away:'Curazao',
    venue:'Kansas City', stadium:'Arrowhead Stadium', city:'Kansas City' },
  { id:'F4', kickoff:'2026-06-21T04:00:00Z', group:'F', home:'Túnez', away:'Japón',
    venue:'Monterrey', stadium:'Estadio BBVA', city:'Monterrey' },

  { id:'H3', kickoff:'2026-06-21T16:00:00Z', group:'H', home:'España', away:'Arabia Saudí',
    venue:'Atlanta', stadium:'Mercedes-Benz Stadium', city:'Atlanta' },
  { id:'G3', kickoff:'2026-06-21T19:00:00Z', group:'G', home:'Bélgica', away:'Irán',
    venue:'Los Ángeles', stadium:'SoFi Stadium', city:'Inglewood' },
  { id:'H4', kickoff:'2026-06-21T22:00:00Z', group:'H', home:'Uruguay', away:'Cabo Verde',
    venue:'Miami', stadium:'Hard Rock Stadium', city:'Miami Gardens' },
  { id:'G4', kickoff:'2026-06-22T01:00:00Z', group:'G', home:'Nueva Zelanda', away:'Egipto',
    venue:'Vancouver', stadium:'BC Place', city:'Vancouver' },

  { id:'J3', kickoff:'2026-06-22T17:00:00Z', group:'J', home:'Argentina', away:'Austria',
    venue:'Dallas', stadium:'AT&T Stadium', city:'Arlington', isArgentina:true },
  { id:'I3', kickoff:'2026-06-22T21:00:00Z', group:'I', home:'Francia', away:'Irak',
    venue:'Filadelfia', stadium:'Lincoln Financial Field', city:'Filadelfia' },
  { id:'I4', kickoff:'2026-06-23T00:00:00Z', group:'I', home:'Noruega', away:'Senegal',
    venue:'Nueva York/NJ', stadium:'MetLife Stadium', city:'East Rutherford' },
  { id:'J4', kickoff:'2026-06-23T03:00:00Z', group:'J', home:'Jordania', away:'Argelia',
    venue:'San Francisco', stadium:"Levi's Stadium", city:'Santa Clara' },

  { id:'K3', kickoff:'2026-06-23T17:00:00Z', group:'K', home:'Portugal', away:'Uzbekistán',
    venue:'Houston', stadium:'NRG Stadium', city:'Houston' },
  { id:'L3', kickoff:'2026-06-23T20:00:00Z', group:'L', home:'Inglaterra', away:'Ghana',
    venue:'Boston', stadium:'Gillette Stadium', city:'Foxborough' },
  { id:'L4', kickoff:'2026-06-23T23:00:00Z', group:'L', home:'Panamá', away:'Croacia',
    venue:'Toronto', stadium:'BMO Field', city:'Toronto' },
  { id:'K4', kickoff:'2026-06-24T02:00:00Z', group:'K', home:'Colombia', away:'RD Congo',
    venue:'Zapopan', stadium:'Estadio Akron', city:'Zapopan' },

  // ════════════════════════════════════════════
  // FECHA 3  (24–27 jun) — última jornada, simultáneos por grupo
  // ════════════════════════════════════════════
  { id:'B5', kickoff:'2026-06-24T19:00:00Z', group:'B', home:'Suiza', away:'Canadá',
    venue:'Vancouver', stadium:'BC Place', city:'Vancouver' },
  { id:'B6', kickoff:'2026-06-24T19:00:00Z', group:'B', home:'Bosnia y Herz.', away:'Qatar',
    venue:'Seattle', stadium:'Lumen Field', city:'Seattle' },
  { id:'C5', kickoff:'2026-06-24T22:00:00Z', group:'C', home:'Escocia', away:'Brasil',
    venue:'Miami', stadium:'Hard Rock Stadium', city:'Miami Gardens' },
  { id:'C6', kickoff:'2026-06-24T22:00:00Z', group:'C', home:'Marruecos', away:'Haití',
    venue:'Atlanta', stadium:'Mercedes-Benz Stadium', city:'Atlanta' },
  { id:'A5', kickoff:'2026-06-25T01:00:00Z', group:'A', home:'Rep. Checa', away:'México',
    venue:'Ciudad de México', stadium:'Estadio Azteca', city:'Ciudad de México' },
  { id:'A6', kickoff:'2026-06-25T01:00:00Z', group:'A', home:'Sudáfrica', away:'Corea del Sur',
    venue:'Monterrey', stadium:'Estadio BBVA', city:'Monterrey' },

  { id:'E5', kickoff:'2026-06-25T20:00:00Z', group:'E', home:'Curazao', away:'Costa de Marfil',
    venue:'Filadelfia', stadium:'Lincoln Financial Field', city:'Filadelfia' },
  { id:'E6', kickoff:'2026-06-25T20:00:00Z', group:'E', home:'Ecuador', away:'Alemania',
    venue:'Nueva York/NJ', stadium:'MetLife Stadium', city:'East Rutherford' },
  { id:'F5', kickoff:'2026-06-25T23:00:00Z', group:'F', home:'Japón', away:'Suecia',
    venue:'Dallas', stadium:'AT&T Stadium', city:'Arlington' },
  { id:'F6', kickoff:'2026-06-25T23:00:00Z', group:'F', home:'Túnez', away:'Países Bajos',
    venue:'Kansas City', stadium:'Arrowhead Stadium', city:'Kansas City' },
  { id:'D5', kickoff:'2026-06-26T02:00:00Z', group:'D', home:'Turquía', away:'Estados Unidos',
    venue:'Los Ángeles', stadium:'SoFi Stadium', city:'Inglewood' },
  { id:'D6', kickoff:'2026-06-26T02:00:00Z', group:'D', home:'Paraguay', away:'Australia',
    venue:'Santa Clara', stadium:"Levi's Stadium", city:'Santa Clara' },

  { id:'I5', kickoff:'2026-06-26T19:00:00Z', group:'I', home:'Noruega', away:'Francia',
    venue:'Boston', stadium:'Gillette Stadium', city:'Foxborough' },
  { id:'I6', kickoff:'2026-06-26T19:00:00Z', group:'I', home:'Senegal', away:'Irak',
    venue:'Toronto', stadium:'BMO Field', city:'Toronto' },
  { id:'H5', kickoff:'2026-06-27T00:00:00Z', group:'H', home:'Cabo Verde', away:'Arabia Saudí',
    venue:'Houston', stadium:'NRG Stadium', city:'Houston' },
  { id:'H6', kickoff:'2026-06-27T00:00:00Z', group:'H', home:'Uruguay', away:'España',
    venue:'Zapopan', stadium:'Estadio Akron', city:'Zapopan' },
  { id:'G5', kickoff:'2026-06-27T03:00:00Z', group:'G', home:'Egipto', away:'Irán',
    venue:'Seattle', stadium:'Lumen Field', city:'Seattle' },
  { id:'G6', kickoff:'2026-06-27T03:00:00Z', group:'G', home:'Nueva Zelanda', away:'Bélgica',
    venue:'Vancouver', stadium:'BC Place', city:'Vancouver' },

  { id:'L5', kickoff:'2026-06-27T21:00:00Z', group:'L', home:'Panamá', away:'Inglaterra',
    venue:'Nueva York/NJ', stadium:'MetLife Stadium', city:'East Rutherford' },
  { id:'L6', kickoff:'2026-06-27T21:00:00Z', group:'L', home:'Croacia', away:'Ghana',
    venue:'Filadelfia', stadium:'Lincoln Financial Field', city:'Filadelfia' },
  { id:'K5', kickoff:'2026-06-27T23:30:00Z', group:'K', home:'Colombia', away:'Portugal',
    venue:'Miami', stadium:'Hard Rock Stadium', city:'Miami Gardens' },
  { id:'K6', kickoff:'2026-06-27T23:30:00Z', group:'K', home:'RD Congo', away:'Uzbekistán',
    venue:'Atlanta', stadium:'Mercedes-Benz Stadium', city:'Atlanta' },
  { id:'J5', kickoff:'2026-06-28T02:00:00Z', group:'J', home:'Argelia', away:'Austria',
    venue:'Kansas City', stadium:'Arrowhead Stadium', city:'Kansas City' },
  { id:'J6', kickoff:'2026-06-28T02:00:00Z', group:'J', home:'Jordania', away:'Argentina',
    venue:'Dallas', stadium:'AT&T Stadium', city:'Arlington', isArgentina:true },
]

export const BASE_MATCHES: Match[] = RAW_MATCHES.map(buildMatch)

// ─── NOTICIAS ────────────────────────────────────────────────────────────────
// Las noticias se migraron a archivos Markdown en `content/noticias/<slug>/index.md`.
// Ver `lib/noticias.ts` para la capa de lectura y `NOTICIAS.md` para el flujo editorial.
// Se mantiene `FEATURED_TEAM_SLUGS` porque lo consume `app/page.tsx` (selecciones destacadas).

export const FEATURED_TEAM_SLUGS = [
	'argentina','brasil','francia','espana','alemania',
	'portugal','paises-bajos','inglaterra','estados-unidos','mexico',
]
